### ISSUE TITLE
Apt::Source[lldpd]: has no parameter named 'keyring'

### ISSUE THREAD

**Issue by verhoevenv** [voxpupuli/puppet-lldpd#139]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 
- Ruby:
- Distribution: Debian 11
- Module version: 4.0.2

## How to reproduce (e.g Puppet code you use)

Combine puppet-lldpd with older puppetlabs-apt (7.4.2 in our case)

## What are you seeing
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[lldpd]: has no parameter named 'keyring' (file: /etc/puppetlabs/code/environments/production/modules/lldpd/manifests/init.pp, line: 53) on node <node>`

## Any additional information you'd like to impart

On puppetlabs-apt 7.4.2 apt::source indeed doesn't have the keyring parameter. It was introduced in 8.1.0 (https://github.com/puppetlabs/puppetlabs-apt/pull/991). Probably the dependency should be bumped?

**Comment by b4ldr** [comment]
yuo will need to use at least puppetlabs/apt 8.1.0.  i have sent a fix to update metadata.json
