### ISSUE TITLE
Debian Repo key has changed, fingerprint needs to be updated

### ISSUE THREAD

**Issue by jchonig** [voxpupuli/puppet-lldpd#87]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

Use the module with default parameters on Debian or Ubuntu.

Run `apt update` or similar

## What are you seeing

Failure to update from the configured repo

## Output log

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_16.04  InRelease: The following signatures were invalid: KEYEXPIRED 1593100053
W: Failed to fetch http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_16.04/InRelease  The following signatures were invalid: KEYEXPIRED 1593100053
```

**Comment by bastelfreak** [comment]
Hi @jchonig, thanks for raising the issue. Can you provide a patch for this?

**Comment by jchonig** [comment]
I mis-understood the fix.  The key fingerprint is the same, I just needed to refresh the key with:

```
wget http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_16.04/Release.key
sudo apt-key add Release.key
```
